# Generated by Django 4.0.6 on 2022-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='add_to_about',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='add_to_home',
            field=models.BooleanField(),
        ),
    ]
